import { PropsWithChildren } from 'react';

import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';

import './styles/globals.scss';

const publicSans = Public_Sans({
  variable: '--font-public-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: 'Akinai商い',
    template: '%s | Akinai商い',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={`${publicSans.variable} wrapper`}>
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
